"""add_m3_ingestion_foundation

Revision ID: 67fe8ebaf96b
Revises: a8027288583a
Create Date: 2026-08-29 05:15:35.623884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '67fe8ebaf96b'
down_revision: Union[str, Sequence[str], None] = 'a8027288583a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evidence_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('evidence_reference', sa.String(length=80), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('artifact_type', sa.String(length=50), nullable=False),
    sa.Column('original_record_id', sa.String(length=255), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('application', sa.String(length=150), nullable=True),
    sa.Column('searchable_text', sa.Text(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('raw_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('parser_identifier', sa.String(length=100), nullable=False),
    sa.Column('parser_version', sa.String(length=50), nullable=False),
    sa.Column('imported_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['evidence_sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'original_record_id', name='uq_evidence_source_record')
    )
    op.create_index('ix_evidence_case_timestamp', 'evidence_items', ['case_id', 'occurred_at'], unique=False)
    op.create_index('ix_evidence_case_type', 'evidence_items', ['case_id', 'artifact_type'], unique=False)
    op.create_index(op.f('ix_evidence_items_evidence_reference'), 'evidence_items', ['evidence_reference'], unique=True)
    op.create_index('ix_evidence_source_type', 'evidence_items', ['source_id', 'artifact_type'], unique=False)
    op.create_table('processing_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('stage', sa.String(length=40), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('diagnostics', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('stage_history', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['evidence_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processing_jobs_source_id'), 'processing_jobs', ['source_id'], unique=False)
    op.create_index(op.f('ix_processing_jobs_status'), 'processing_jobs', ['status'], unique=False)
    op.add_column('evidence_sources', sa.Column('original_filename', sa.String(length=255), nullable=True))
    op.add_column('evidence_sources', sa.Column('storage_key', sa.String(length=255), nullable=True))
    op.add_column('evidence_sources', sa.Column('file_size', sa.BigInteger(), nullable=True))
    op.add_column('evidence_sources', sa.Column('sha256', sa.String(length=64), nullable=True))
    op.add_column('evidence_sources', sa.Column('imported_by_id', sa.UUID(), nullable=True))
    op.add_column('evidence_sources', sa.Column('imported_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('evidence_sources', sa.Column('parser_identifier', sa.String(length=100), nullable=True))
    op.add_column('evidence_sources', sa.Column('parser_version', sa.String(length=50), nullable=True))
    op.add_column('evidence_sources', sa.Column('processing_state', sa.String(length=40), server_default='registered', nullable=False))
    op.add_column('evidence_sources', sa.Column('processing_stage', sa.String(length=40), nullable=True))
    op.add_column('evidence_sources', sa.Column('is_partial', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('evidence_sources', sa.Column('error_summary', sa.Text(), nullable=True))
    op.add_column('evidence_sources', sa.Column('evidence_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('evidence_sources', sa.Column('evidence_counts', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.create_index(op.f('ix_evidence_sources_imported_by_id'), 'evidence_sources', ['imported_by_id'], unique=False)
    op.create_index(op.f('ix_evidence_sources_processing_state'), 'evidence_sources', ['processing_state'], unique=False)
    op.create_index(op.f('ix_evidence_sources_sha256'), 'evidence_sources', ['sha256'], unique=False)
    op.create_unique_constraint('uq_evidence_sources_storage_key', 'evidence_sources', ['storage_key'])
    op.create_foreign_key('fk_evidence_sources_imported_by_id_users', 'evidence_sources', 'users', ['imported_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_evidence_sources_imported_by_id_users', 'evidence_sources', type_='foreignkey')
    op.drop_constraint('uq_evidence_sources_storage_key', 'evidence_sources', type_='unique')
    op.drop_index(op.f('ix_evidence_sources_sha256'), table_name='evidence_sources')
    op.drop_index(op.f('ix_evidence_sources_processing_state'), table_name='evidence_sources')
    op.drop_index(op.f('ix_evidence_sources_imported_by_id'), table_name='evidence_sources')
    op.drop_column('evidence_sources', 'evidence_counts')
    op.drop_column('evidence_sources', 'evidence_count')
    op.drop_column('evidence_sources', 'error_summary')
    op.drop_column('evidence_sources', 'is_partial')
    op.drop_column('evidence_sources', 'processing_stage')
    op.drop_column('evidence_sources', 'processing_state')
    op.drop_column('evidence_sources', 'parser_version')
    op.drop_column('evidence_sources', 'parser_identifier')
    op.drop_column('evidence_sources', 'imported_at')
    op.drop_column('evidence_sources', 'imported_by_id')
    op.drop_column('evidence_sources', 'sha256')
    op.drop_column('evidence_sources', 'file_size')
    op.drop_column('evidence_sources', 'storage_key')
    op.drop_column('evidence_sources', 'original_filename')
    op.drop_index(op.f('ix_processing_jobs_status'), table_name='processing_jobs')
    op.drop_index(op.f('ix_processing_jobs_source_id'), table_name='processing_jobs')
    op.drop_table('processing_jobs')
    op.drop_index('ix_evidence_source_type', table_name='evidence_items')
    op.drop_index(op.f('ix_evidence_items_evidence_reference'), table_name='evidence_items')
    op.drop_index('ix_evidence_case_type', table_name='evidence_items')
    op.drop_index('ix_evidence_case_timestamp', table_name='evidence_items')
    op.drop_table('evidence_items')
    # ### end Alembic commands ###
